// Command command-inventory generates the pinned Beads v1.2.1 CLI inventory.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const probeFileName = "beadshx_inventory_probe_test.go"

type sourceLock struct {
	SchemaVersion       int    `json:"schemaVersion"`
	Project             string `json:"project"`
	Version             string `json:"version"`
	Commit              string `json:"commit"`
	Remote              string `json:"remote"`
	Go                  string `json:"go"`
	ModulePathPolicy    string `json:"modulePathPolicy"`
	OracleBinaryName    string `json:"oracleBinaryName"`
	CandidateBinaryName string `json:"candidateBinaryName"`
}

type goListPackage struct {
	Dir        string
	ImportPath string
	GoFiles    []string
	CgoFiles   []string
}

func main() {
	repositoryFlag := flag.String("repository", ".", "BeadsHX repository root")
	policyFlag := flag.String("policy", "compatibility/command-inventory-policy.json", "inventory policy path, relative to the repository")
	outputFlag := flag.String("output", "compatibility/upstream-v1.2.1-command-inventory.json.gz", "inventory output path, relative to the repository")
	checkFlag := flag.Bool("check", false, "compare generated bytes with the existing output")
	flag.Parse()

	if err := run(*repositoryFlag, *policyFlag, *outputFlag, *checkFlag); err != nil {
		fmt.Fprintf(os.Stderr, "command inventory: %v\n", err)
		os.Exit(1)
	}
}

func run(repositoryInput string, policyInput string, outputInput string, check bool) error {
	repository, err := canonicalDirectory(repositoryInput)
	if err != nil {
		return err
	}
	policyPath, err := repositoryPath(repository, policyInput)
	if err != nil {
		return fmt.Errorf("policy: %w", err)
	}
	outputPath, err := repositoryPath(repository, outputInput)
	if err != nil {
		return fmt.Errorf("output: %w", err)
	}
	policy, err := loadJSON[inventoryPolicy](policyPath)
	if err != nil {
		return fmt.Errorf("load policy: %w", err)
	}
	lock, err := loadJSON[sourceLock](filepath.Join(repository, "upstream", "locks", "beads-v1.2.1.json"))
	if err != nil {
		return fmt.Errorf("load source lock: %w", err)
	}
	if err := validateAuthority(repository, lock, policy); err != nil {
		return err
	}

	scratch, err := os.MkdirTemp("", "beadshx-command-inventory-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(scratch) }()
	sourceRoot := filepath.Join(scratch, "source")
	if err := clonePinnedSource(repository, sourceRoot, lock.Commit); err != nil {
		return err
	}
	if err := installProbe(repository, sourceRoot); err != nil {
		return err
	}
	userCache, err := os.UserCacheDir()
	if err != nil {
		return fmt.Errorf("resolve command inventory cache: %w", err)
	}

	runner := containerRunner{
		sourceRoot: sourceRoot,
		cacheRoot:  filepath.Join(userCache, "beadshx", "command-inventory"),
		image:      policy.Container,
	}
	if err := runner.prepare(policy.GoVersion); err != nil {
		return err
	}
	var snapshots []runtimeSnapshot
	activeFiles := make(map[string]map[string]bool)
	packageDirectories := make(map[string]bool)
	for _, selectedProfile := range policy.Profiles {
		packages, err := runner.listPackages(selectedProfile)
		if err != nil {
			return fmt.Errorf("list packages for %s: %w", selectedProfile.ID, err)
		}
		mergePackageFiles(selectedProfile.ID, packages, activeFiles, packageDirectories)
		probeBinary, err := runner.buildProbe(selectedProfile)
		if err != nil {
			return fmt.Errorf("build probe for %s: %w", selectedProfile.ID, err)
		}
		for _, activation := range policy.Activations {
			snapshot, err := runner.probe(selectedProfile, activation, probeBinary)
			if err != nil {
				return fmt.Errorf("probe %s/%s: %w", selectedProfile.ID, activation, err)
			}
			snapshots = append(snapshots, snapshot)
		}
	}
	sort.Slice(snapshots, func(i, j int) bool {
		if snapshots[i].Profile != snapshots[j].Profile {
			return snapshots[i].Profile < snapshots[j].Profile
		}
		return snapshots[i].Activation < snapshots[j].Activation
	})

	sources, err := collectSourceFiles(sourceRoot, activeFiles, packageDirectories)
	if err != nil {
		return err
	}
	if err := validateSemanticCatalog(sourceRoot, sources, policy.Semantics); err != nil {
		return fmt.Errorf("validate semantic catalog: %w", err)
	}
	policyByKind := make(map[string]string, len(policy.Semantics.ObligationPolicies))
	for _, obligationPolicy := range policy.Semantics.ObligationPolicies {
		if obligationPolicy.Kind == "" || obligationPolicy.Resolution == "" {
			return errors.New("semantic obligation policies require kind and resolution")
		}
		if policyByKind[obligationPolicy.Kind] != "" {
			return fmt.Errorf("duplicate obligation policy for %s", obligationPolicy.Kind)
		}
		policyByKind[obligationPolicy.Kind] = obligationPolicy.Resolution
	}
	obligations, err := censusSources(sourceRoot, sources, policyByKind)
	if err != nil {
		return err
	}

	result := inventory{
		SchemaVersion: 1,
		Source:        sourceIdentity{Project: lock.Project, Version: lock.Version, Commit: lock.Commit},
		Toolchain:     toolchainIdentity{Go: "go" + policy.GoVersion, Cobra: policy.CobraVersion},
		Profiles:      append([]profile(nil), policy.Profiles...),
		Activations:   append([]string(nil), policy.Activations...),
		Snapshots:     snapshots,
		Obligations:   obligations,
		Semantics:     policy.Semantics,
	}
	if err := reconcile(&result); err != nil {
		return err
	}
	content, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return err
	}
	content = append(content, '\n')
	content, err = compressCanonicalJSON(content)
	if err != nil {
		return err
	}
	if check {
		// #nosec G304 -- repositoryPath confines outputPath to the reviewed repository root.
		existing, err := os.ReadFile(outputPath)
		if err != nil {
			return err
		}
		if !bytes.Equal(existing, content) {
			want := sha256.Sum256(existing)
			got := sha256.Sum256(content)
			return fmt.Errorf("generated inventory differs: committed=%s generated=%s", hex.EncodeToString(want[:]), hex.EncodeToString(got[:]))
		}
		return nil
	}
	return writeAtomic(outputPath, content)
}

func compressCanonicalJSON(content []byte) ([]byte, error) {
	var output bytes.Buffer
	writer, err := gzip.NewWriterLevel(&output, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	writer.Header.ModTime = time.Unix(0, 0).UTC()
	writer.Header.OS = 255
	if _, err := writer.Write(content); err != nil {
		_ = writer.Close()
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func validateAuthority(repository string, lock sourceLock, policy inventoryPolicy) error {
	if lock.Project != "Beads" || lock.Version != "v1.2.1" || len(lock.Commit) != 40 {
		return fmt.Errorf("unexpected source lock: %#v", lock)
	}
	if policy.SchemaVersion != 1 || policy.SourceCommit != lock.Commit || policy.GoVersion != lock.Go {
		return errors.New("inventory policy does not match the source lock")
	}
	if policy.CobraVersion != "v1.10.2" {
		return fmt.Errorf("unsupported Cobra policy %q", policy.CobraVersion)
	}
	if len(policy.Profiles) == 0 || len(policy.Activations) == 0 || policy.Container == "" {
		return errors.New("inventory policy has no profiles, activations, or container")
	}
	commit, err := gitOutput(repository, "cat-file", "-t", lock.Commit+"^{commit}")
	if err != nil || strings.TrimSpace(string(commit)) != "commit" {
		return fmt.Errorf("pinned source commit is unavailable: %w", err)
	}
	goMod, err := gitOutput(repository, "show", lock.Commit+":go.mod")
	if err != nil {
		return err
	}
	if !bytes.Contains(goMod, []byte("go "+policy.GoVersion+"\n")) ||
		!bytes.Contains(goMod, []byte("github.com/spf13/cobra "+policy.CobraVersion)) {
		return errors.New("pinned go.mod does not match the declared Go and Cobra versions")
	}
	return nil
}

func clonePinnedSource(repository string, destination string, commit string) error {
	if _, err := gitOutput("", "clone", "--shared", "--no-checkout", "--quiet", repository, destination); err != nil {
		return fmt.Errorf("clone pinned source: %w", err)
	}
	if _, err := gitOutput(destination, "checkout", "--detach", "--quiet", commit); err != nil {
		return fmt.Errorf("checkout pinned source: %w", err)
	}
	actual, err := gitOutput(destination, "rev-parse", "HEAD")
	if err != nil || strings.TrimSpace(string(actual)) != commit {
		return errors.New("scratch checkout does not match the pinned commit")
	}
	return nil
}

func installProbe(repository string, sourceRoot string) error {
	templatePath := filepath.Join(repository, "scripts", "beadshx", "command-inventory", "probe_test.go.txt")
	// #nosec G304 -- templatePath is a fixed path under the canonical repository root.
	content, err := os.ReadFile(templatePath)
	if err != nil {
		return err
	}
	commandRoot := filepath.Join(sourceRoot, "cmd", "bd")
	entries, err := os.ReadDir(commandRoot)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), "_test.go") {
			if err := os.Remove(filepath.Join(commandRoot, entry.Name())); err != nil {
				return err
			}
		}
	}
	return os.WriteFile(filepath.Join(commandRoot, probeFileName), content, 0o600)
}

type containerRunner struct {
	sourceRoot string
	cacheRoot  string
	image      string
}

func (runner containerRunner) prepare(goVersion string) error {
	if _, err := exec.LookPath("docker"); err != nil {
		return errors.New("Docker is required for the exact Linux/AMD64 inventory profiles")
	}
	if err := os.MkdirAll(filepath.Join(runner.cacheRoot, "gomod"), 0o700); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(runner.cacheRoot, "gobuild"), 0o700); err != nil {
		return err
	}
	for _, path := range []string{"home", "xdg", "tmp", "cwd"} {
		if err := os.MkdirAll(filepath.Join(runner.sourceRoot, ".beadshx-sandbox", path), 0o700); err != nil {
			return err
		}
	}
	for _, path := range []string{"home", "xdg", "tmp"} {
		if err := os.MkdirAll(filepath.Join(runner.cacheRoot, path), 0o700); err != nil {
			return err
		}
	}
	version, err := runner.run(nil, false, "go", "version")
	if err != nil {
		return fmt.Errorf("verify container Go: %w", err)
	}
	if !strings.Contains(string(version), "go"+goVersion+" ") {
		return fmt.Errorf("container reports unexpected Go version: %s", strings.TrimSpace(string(version)))
	}
	return nil
}

func (runner containerRunner) listPackages(selected profile) ([]goListPackage, error) {
	// Package listing is the preparation boundary: it downloads only the
	// checksum-locked cmd/bd build closure. Runtime probes that follow use the
	// populated cache with networking disabled.
	output, err := runner.run(&selected, false, "go", "list", "-deps", "-json", "./cmd/bd")
	if err != nil {
		return nil, err
	}
	decoder := json.NewDecoder(bytes.NewReader(output))
	var packages []goListPackage
	for {
		var item goListPackage
		if err := decoder.Decode(&item); err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return nil, err
		}
		if item.Dir == "/workspace" || strings.HasPrefix(item.Dir, "/workspace/") {
			packages = append(packages, item)
		}
	}
	if len(packages) == 0 {
		return nil, errors.New("go list returned no first-party packages")
	}
	return packages, nil
}

func (runner containerRunner) buildProbe(selected profile) (string, error) {
	binaryName := ".beadshx-probe-" + selected.ID
	binaryPath := filepath.Join(runner.sourceRoot, binaryName)
	_ = os.Remove(binaryPath)
	if _, err := runner.run(&selected, true,
		"go", "test", "-c", "-tags="+strings.Join(selected.BuildTags, ","),
		"-o", "/workspace/"+binaryName, "./cmd/bd",
	); err != nil {
		return "", err
	}
	return "/workspace/" + binaryName, nil
}

func (runner containerRunner) probe(selected profile, activation string, binary string) (runtimeSnapshot, error) {
	outputName := ".beadshx-inventory-" + selected.ID + "-" + activation + ".json"
	outputPath := filepath.Join(runner.sourceRoot, outputName)
	_ = os.Remove(outputPath)
	extra := []string{
		"-e", "HOME=/workspace/.beadshx-sandbox/home",
		"-e", "XDG_CONFIG_HOME=/workspace/.beadshx-sandbox/xdg",
		"-e", "TMPDIR=/workspace/.beadshx-sandbox/tmp",
		"-e", "BEADSHX_INVENTORY_PROFILE=" + selected.ID,
		"-e", "BEADSHX_INVENTORY_ACTIVATION=" + activation,
		"-e", "BEADSHX_INVENTORY_OUTPUT=/workspace/" + outputName,
		"-e", "BEADSHX_INVENTORY_CWD=/workspace/.beadshx-sandbox/cwd",
	}
	if _, err := runner.runWithExtra(&selected, true, extra, binary, "-test.run=^TestBeadsHXInventoryProbe$", "-test.count=1"); err != nil {
		return runtimeSnapshot{}, err
	}
	// #nosec G304 -- outputPath is generated inside the disposable scratch checkout.
	content, err := os.ReadFile(outputPath)
	if err != nil {
		return runtimeSnapshot{}, err
	}
	var snapshot runtimeSnapshot
	if err := json.Unmarshal(content, &snapshot); err != nil {
		return runtimeSnapshot{}, err
	}
	if snapshot.Profile != selected.ID || snapshot.Activation != activation {
		return runtimeSnapshot{}, errors.New("probe output identity mismatch")
	}
	if err := requireSandboxEmpty(filepath.Join(runner.sourceRoot, ".beadshx-sandbox")); err != nil {
		return runtimeSnapshot{}, err
	}
	return snapshot, nil
}

func (runner containerRunner) run(selected *profile, networkDisabled bool, command ...string) ([]byte, error) {
	return runner.runWithExtra(selected, networkDisabled, nil, command...)
}

func (runner containerRunner) runWithExtra(selected *profile, networkDisabled bool, extra []string, command ...string) ([]byte, error) {
	arguments := []string{"run", "--rm", "--platform", "linux/amd64", "--user", strconv.Itoa(os.Getuid()) + ":" + strconv.Itoa(os.Getgid())}
	if networkDisabled {
		arguments = append(arguments, "--network", "none")
	}
	arguments = append(arguments,
		"-e", "HOME=/beadshx-cache/home",
		"-e", "XDG_CONFIG_HOME=/beadshx-cache/xdg",
		"-e", "TMPDIR=/beadshx-cache/tmp",
		"-e", "GOMODCACHE=/beadshx-cache/gomod",
		"-e", "GOCACHE=/beadshx-cache/gobuild",
		"-e", "GOTOOLCHAIN=local",
		"-e", "GOFLAGS=-buildvcs=false",
		"-e", "GOTELEMETRY=off",
		"-e", "TZ=UTC",
		"-e", "LC_ALL=C.UTF-8",
		"-e", "BEADS_NO_AUTO_FLUSH=1",
		"-e", "BEADS_TELEMETRY_DISABLED=1",
	)
	if selected != nil {
		cgo := "0"
		if selected.CGOEnabled {
			cgo = "1"
		}
		arguments = append(arguments,
			"-e", "GOOS="+selected.GOOS,
			"-e", "GOARCH="+selected.GOARCH,
			"-e", "CGO_ENABLED="+cgo,
		)
	}
	arguments = append(arguments, extra...)
	arguments = append(arguments,
		"-v", runner.sourceRoot+":/workspace:rw",
		"-v", runner.cacheRoot+":/beadshx-cache:rw",
		"-w", "/workspace", runner.image,
	)
	arguments = append(arguments, command...)
	return commandStdout("", "docker", arguments...)
}

func mergePackageFiles(profileID string, packages []goListPackage, active map[string]map[string]bool, directories map[string]bool) {
	for _, item := range packages {
		relativeDirectory := strings.TrimPrefix(strings.TrimPrefix(item.Dir, "/workspace"), "/")
		directories[relativeDirectory] = true
		for _, name := range append(append([]string(nil), item.GoFiles...), item.CgoFiles...) {
			path := filepath.ToSlash(filepath.Join(relativeDirectory, name))
			if active[path] == nil {
				active[path] = make(map[string]bool)
			}
			active[path][profileID] = true
		}
	}
}

func collectSourceFiles(root string, active map[string]map[string]bool, directories map[string]bool) ([]sourceFile, error) {
	var files []sourceFile
	for directory := range directories {
		entries, err := os.ReadDir(filepath.Join(root, filepath.FromSlash(directory)))
		if err != nil {
			return nil, err
		}
		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
				continue
			}
			path := filepath.ToSlash(filepath.Join(directory, entry.Name()))
			var profiles []string
			for profileID := range active[path] {
				profiles = append(profiles, profileID)
			}
			sort.Strings(profiles)
			files = append(files, sourceFile{Path: path, ActiveProfiles: profiles})
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func reconcile(result *inventory) error {
	if len(result.Snapshots) != len(result.Profiles)*len(result.Activations) {
		return errors.New("profile and activation matrix is incomplete")
	}
	coverage := coverageSummary{SnapshotCount: len(result.Snapshots), ObligationsByKind: make(map[string]int)}
	for _, snapshot := range result.Snapshots {
		if len(snapshot.Commands) == 0 {
			return fmt.Errorf("snapshot %s/%s has no commands", snapshot.Profile, snapshot.Activation)
		}
		if len(snapshot.GlobalFlags) != 0 {
			coverage.UnexpectedGlobal += len(snapshot.GlobalFlags)
			return fmt.Errorf("snapshot %s/%s has unexpected global flags: %v", snapshot.Profile, snapshot.Activation, snapshot.GlobalFlags)
		}
		commands := make(map[string]commandRecord, len(snapshot.Commands))
		flags := make(map[string]bool, len(snapshot.Flags))
		for _, command := range snapshot.Commands {
			if command.ID == "" || commands[command.ID].ID != "" {
				return fmt.Errorf("snapshot %s/%s has a missing or duplicate command ID %q", snapshot.Profile, snapshot.Activation, command.ID)
			}
			commands[command.ID] = command
		}
		if commands["cmd:bd"].ID == "" {
			return fmt.Errorf("snapshot %s/%s has no canonical root", snapshot.Profile, snapshot.Activation)
		}
		for _, command := range snapshot.Commands {
			if command.ParentID != "" && commands[command.ParentID].ID == "" {
				return fmt.Errorf("command %s has unknown parent %s", command.ID, command.ParentID)
			}
			for _, disposition := range []string{command.SemanticDispositions.Environment, command.SemanticDispositions.Stdin, command.SemanticDispositions.Output, command.SemanticDispositions.Completion} {
				if disposition == "" || disposition == "unknown" {
					return fmt.Errorf("command %s has an unresolved semantic disposition", command.ID)
				}
			}
		}
		for _, declaration := range snapshot.Flags {
			if declaration.ID == "" || flags[declaration.ID] {
				return fmt.Errorf("snapshot %s/%s has a missing or duplicate flag ID %q", snapshot.Profile, snapshot.Activation, declaration.ID)
			}
			if commands[declaration.CommandID].ID == "" {
				return fmt.Errorf("flag %s has unknown command %s", declaration.ID, declaration.CommandID)
			}
			flags[declaration.ID] = true
		}
		for _, command := range snapshot.Commands {
			for _, ref := range append(append(append(append([]string(nil), command.LocalFlagRefs...), command.PersistentFlagRefs...), command.InheritedFlagRefs...), command.EffectiveFlagRefs...) {
				if !flags[ref] {
					return fmt.Errorf("command %s has orphan flag reference %s", command.ID, ref)
				}
			}
		}
		if err := checkKnownSurface(snapshot, commands); err != nil {
			return err
		}
		coverage.CommandInstances += len(snapshot.Commands)
		coverage.FlagDeclarations += len(snapshot.Flags)
	}
	if err := checkProfileAndActivationMatrix(result.Snapshots); err != nil {
		coverage.Conflicting++
		return err
	}
	for _, obligation := range result.Obligations {
		coverage.ObligationCount++
		coverage.ObligationsByKind[obligation.Kind]++
		if obligation.Resolution == "" || obligation.Resolution == "unknown" {
			coverage.Unresolved++
		}
	}
	if coverage.Unresolved != 0 || coverage.Orphaned != 0 || coverage.Conflicting != 0 || coverage.UnexpectedGlobal != 0 {
		return fmt.Errorf("inventory does not close: %#v", coverage)
	}
	result.Coverage = coverage
	return nil
}

func checkProfileAndActivationMatrix(snapshots []runtimeSnapshot) error {
	byKey := make(map[string]runtimeSnapshot, len(snapshots))
	for _, snapshot := range snapshots {
		key := snapshot.Profile + "/" + snapshot.Activation
		if _, exists := byKey[key]; exists {
			return fmt.Errorf("duplicate snapshot %s", key)
		}
		byKey[key] = snapshot
	}
	for _, profileID := range []string{"portable-nocgo", "release-cgo"} {
		normal, normalOK := byKey[profileID+"/normal"]
		completion, completionOK := byKey[profileID+"/completion"]
		if !normalOK || !completionOK {
			return fmt.Errorf("missing activation pair for %s", profileID)
		}
		completionOnly, normalOnly := setDifference(commandIDs(completion.Commands), commandIDs(normal.Commands))
		if !equalStrings(completionOnly, []string{"cmd:bd/__complete"}) || len(normalOnly) != 0 {
			return fmt.Errorf("unexpected activation command delta for %s: completion=%v normal=%v", profileID, completionOnly, normalOnly)
		}
		completionFlags, normalFlags := setDifference(flagIDs(completion.Flags), flagIDs(normal.Flags))
		if !equalStrings(completionFlags, []string{"flag:cmd:bd/__complete/--help"}) || len(normalFlags) != 0 {
			return fmt.Errorf("unexpected activation flag delta for %s: completion=%v normal=%v", profileID, completionFlags, normalFlags)
		}
	}

	release := byKey["release-cgo/normal"]
	portable := byKey["portable-nocgo/normal"]
	releaseOnly, portableOnly := setDifference(commandIDs(release.Commands), commandIDs(portable.Commands))
	expectedCommands := []string{
		"cmd:bd/federation/add-peer",
		"cmd:bd/federation/list-peers",
		"cmd:bd/federation/remove-peer",
		"cmd:bd/federation/status",
		"cmd:bd/federation/sync",
	}
	if !equalStrings(releaseOnly, expectedCommands) || len(portableOnly) != 0 {
		return fmt.Errorf("unexpected profile command delta: release=%v portable=%v", releaseOnly, portableOnly)
	}
	releaseFlags, portableFlags := setDifference(flagIDs(release.Flags), flagIDs(portable.Flags))
	expectedFlags := []string{
		"flag:cmd:bd/federation/add-peer/--help",
		"flag:cmd:bd/federation/add-peer/--password",
		"flag:cmd:bd/federation/add-peer/--sovereignty",
		"flag:cmd:bd/federation/add-peer/--user",
		"flag:cmd:bd/federation/list-peers/--help",
		"flag:cmd:bd/federation/remove-peer/--help",
		"flag:cmd:bd/federation/status/--help",
		"flag:cmd:bd/federation/status/--peer",
		"flag:cmd:bd/federation/sync/--help",
		"flag:cmd:bd/federation/sync/--peer",
		"flag:cmd:bd/federation/sync/--strategy",
	}
	if !equalStrings(releaseFlags, expectedFlags) || len(portableFlags) != 0 {
		return fmt.Errorf("unexpected profile flag delta: release=%v portable=%v", releaseFlags, portableFlags)
	}
	return nil
}

func commandIDs(commands []commandRecord) []string {
	ids := make([]string, 0, len(commands))
	for _, command := range commands {
		ids = append(ids, command.ID)
	}
	sort.Strings(ids)
	return ids
}

func flagIDs(flags []flagDeclaration) []string {
	ids := make([]string, 0, len(flags))
	for _, declaration := range flags {
		ids = append(ids, declaration.ID)
	}
	sort.Strings(ids)
	return ids
}

func setDifference(left []string, right []string) ([]string, []string) {
	leftSet := make(map[string]bool, len(left))
	rightSet := make(map[string]bool, len(right))
	for _, value := range left {
		leftSet[value] = true
	}
	for _, value := range right {
		rightSet[value] = true
	}
	var leftOnly []string
	var rightOnly []string
	for value := range leftSet {
		if !rightSet[value] {
			leftOnly = append(leftOnly, value)
		}
	}
	for value := range rightSet {
		if !leftSet[value] {
			rightOnly = append(rightOnly, value)
		}
	}
	sort.Strings(leftOnly)
	sort.Strings(rightOnly)
	return leftOnly, rightOnly
}

func equalStrings(left []string, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func checkKnownSurface(snapshot runtimeSnapshot, commands map[string]commandRecord) error {
	require := func(id string) error {
		if commands[id].ID == "" {
			return fmt.Errorf("snapshot %s/%s is missing %s", snapshot.Profile, snapshot.Activation, id)
		}
		return nil
	}
	for _, id := range []string{"cmd:bd/send-metrics", "cmd:bd/codex-hook", "cmd:bd/db-proxy-child", "cmd:bd/show", "cmd:bd/help", "cmd:bd/completion", "cmd:bd/completion/bash", "cmd:bd/completion/fish", "cmd:bd/completion/powershell", "cmd:bd/completion/zsh", "cmd:bd/federation"} {
		if err := require(id); err != nil {
			return err
		}
	}
	for _, id := range []string{"cmd:bd/send-metrics", "cmd:bd/codex-hook", "cmd:bd/db-proxy-child"} {
		if !commands[id].Hidden {
			return fmt.Errorf("known hidden command %s is visible", id)
		}
	}
	if !contains(commands["cmd:bd/show"].Aliases, "view") {
		return errors.New("show alias view is missing")
	}
	if snapshot.Activation == "completion" {
		if err := require("cmd:bd/__complete"); err != nil {
			return err
		}
		if !contains(commands["cmd:bd/__complete"].Aliases, cobraNoDescAlias()) {
			return errors.New("transient completion alias is missing")
		}
	} else if commands["cmd:bd/__complete"].ID != "" {
		return errors.New("transient completion command leaked into normal activation")
	}
	children := 0
	for _, command := range commands {
		if command.ParentID == "cmd:bd/federation" {
			children++
		}
	}
	if snapshot.Profile == "release-cgo" && children != 5 {
		return fmt.Errorf("release-cgo federation has %d children; expected 5", children)
	}
	if snapshot.Profile == "portable-nocgo" && children != 0 {
		return fmt.Errorf("portable-nocgo federation has %d children; expected 0", children)
	}
	return nil
}

func cobraNoDescAlias() string { return "__completeNoDesc" }

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func requireSandboxEmpty(root string) error {
	return filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == root || entry.IsDir() {
			return nil
		}
		return fmt.Errorf("inventory activation wrote unexpected sandbox file %s", filepath.ToSlash(strings.TrimPrefix(path, root+string(filepath.Separator))))
	})
}

func canonicalDirectory(path string) (string, error) {
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return "", err
	}
	resolved, err = filepath.Abs(resolved)
	if err != nil {
		return "", err
	}
	details, err := os.Stat(resolved)
	if err != nil || !details.IsDir() {
		return "", fmt.Errorf("repository is not a directory: %s", resolved)
	}
	return resolved, nil
}

func repositoryPath(repository string, input string) (string, error) {
	path := input
	if !filepath.IsAbs(path) {
		path = filepath.Join(repository, path)
	}
	path = filepath.Clean(path)
	relative, err := filepath.Rel(repository, path)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", errors.New("path escapes the repository")
	}
	return path, nil
}

func loadJSON[T any](path string) (T, error) {
	var value T
	// #nosec G304 -- every caller passes a fixed or repository-confined policy path.
	content, err := os.ReadFile(path)
	if err != nil {
		return value, err
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&value); err != nil {
		return value, err
	}
	return value, nil
}

func gitOutput(directory string, arguments ...string) ([]byte, error) {
	command := exec.Command("git", arguments...)
	command.Dir = directory
	output, err := command.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("git failed: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return output, nil
}

func commandStdout(directory string, name string, arguments ...string) ([]byte, error) {
	command := exec.Command(name, arguments...)
	command.Dir = directory
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	command.Stdout = &stdout
	command.Stderr = &stderr
	if err := command.Run(); err != nil {
		return nil, fmt.Errorf("%s failed: %w: %s", name, err, strings.TrimSpace(stderr.String()))
	}
	return stdout.Bytes(), nil
}

func writeAtomic(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	candidate, err := os.CreateTemp(filepath.Dir(path), ".command-inventory-*.tmp")
	if err != nil {
		return err
	}
	candidatePath := candidate.Name()
	keep := false
	defer func() {
		_ = candidate.Close()
		if !keep {
			_ = os.Remove(candidatePath)
		}
	}()
	if _, err := candidate.Write(content); err != nil {
		return err
	}
	if err := candidate.Sync(); err != nil {
		return err
	}
	if err := candidate.Close(); err != nil {
		return err
	}
	// #nosec G302 -- the generated compatibility inventory is public repository evidence.
	if err := os.Chmod(candidatePath, 0o644); err != nil {
		return err
	}
	if err := os.Rename(candidatePath, path); err != nil {
		return err
	}
	keep = true
	return nil
}
